# Generated by Django 4.1.3 on 2022-11-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_profile_image_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
